# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Minimal Light"
license = "MIT"
description = ""
homepage = "http://siteforthistheme.com/"
tags = []
features = ["blog"]
min_version = "0.21"

[author]
  name = "Anjjan"
  homepage = "https://ajnarayan.github.io"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
