# theme.toml template for a Hugo theme

name = "Hemingway2"
license = "MIT"
licenselink = "https://gitlab.com/beli3ver/hemingway2/blob/master/LICENSE.md"
homepage = "https://gitlab.com/beli3ver/hemingway2"
tags = ["blog", "font awesome", "highlight.js"]
features = ["html5", "css3", "tags"]
min_version = 0.16

