baseURL = "https://ajnarayan.github.io/"
languageCode = "en-us"
title = "Anjjan Narayan's Homepage"
theme= "cactus"


# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blog"
url = "/articles"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3


[params]

  colortheme = "classic" # dark, light, white, or classic
  description = "Hi! I'm Anjjan and welcome to my little, minimal corner on the Internet. I use this site to share and bookmark various things. I currently work on solving large scale cloud computing problems. This website reflects my own opinions."
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/ajnarayan" # title link for projects list

 # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [[params.social]]
    name = "github"
    link = "https://github.com/ajnarayan"
  [[params.social]]
    name = "linkedin"
    link = "http://www.linkedin.com/in/narayananjjan"