baseURL = "https://github.com/ajnarayan/ajnarayan.github.io"
languageCode = "en-us"
title = "Anjjan Narayan"
theme = "minimal-light"
keywords = ["Blog", "Tech"]

[taxonomies]
tag = "tags"
category = "categories"