name = "Cactus"
license = "MIT"
licenselink = "https://github.com/monkeyWzr/hugo-theme-cactus/blob/master/LICENSE"
description = "A clean, responsive hugo theme for personal blog. Forked from hexo theme cactus created by @probberechts."
tags = ["blog", "responsive", "clean"]
features = ["blog"]
min_version = "0.55"

[author]
  name = "Anjjan"
  homepage = "https://ajnarayan.github.io"